package core


object FifthName {

  object Fbb extends Fifth(-15)
  object Cbb extends Fifth(-14)
  object Gbb extends Fifth(-13)
  object Dbb extends Fifth(-12)
  object Abb extends Fifth(-11)
  object Ebb extends Fifth(-10)
  object Bbb extends Fifth(-9)
  object Fb extends Fifth(-8)
  object Cb extends Fifth(-7)
  object Gb extends Fifth(-6)
  object Db extends Fifth(-5)
  object Ab extends Fifth(-4)
  object Eb extends Fifth(-3)
  object Bb extends Fifth(-2)
  object F extends Fifth(-1)
  object C extends Fifth(0)
  object G extends Fifth(1)
  object D extends Fifth(2)
  object A extends Fifth(3)
  object E extends Fifth(4)
  object B extends Fifth(5)
  object Fs extends Fifth(6)
  object Cs extends Fifth(7)
  object Gs extends Fifth(8)
  object Ds extends Fifth(9)
  object As extends Fifth(10)
  object Es extends Fifth(11)
  object Bs extends Fifth(12)
  object Fss extends Fifth(13)
  object Css extends Fifth(14)
  object Gss extends Fifth(15)
  object Dss extends Fifth(16)
  object Ass extends Fifth(17)
  object Ess extends Fifth(18)
  object Bss extends Fifth(19)

}
